name: Git CI/CD
on:
  push:
    branches:
      - main

jobs:
  run-ci-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Get Last Update
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Run Unit Test
      run: |
        vendor/bin/phpunit WordCheckerTest.php

  run-cd-deploy-cpanel:
    name: Deploy
    runs-on: ubuntu-latest
    needs: run-ci-unit-test
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
        
      - name: Upload to CPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
